### ISSUE TITLE
S3: `RuntimeError: dictionary changed size during iteration`

### ISSUE THREAD

**Issue by alltilla** [axoflow/axosyslog#236]
# AxoSyslog
## Version of AxoSyslog
```
4.7.1.831.ge087d9b+4.7.1_git20240709
```

# Issue
```
Exception in thread Thread-3460:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1431, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/syslog-ng/python/syslogng/modules/s3/s3_destination.py", line 352, in __flush_timed_out_s3_objects
    for s3_object in self.s3_objects.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by lars-planvera** [comment]
Still occurring with AxoSyslog 4.25.0

Tested with:
- Official container image: `ghcr.io/axoflow/axosyslog:4.25.0`
- Python 3.12
- Deployed on Kubernetes through Logging Operator 6.7.0

# Issue

When using hive-type object key for logs:
```
object-key(
            "logs/env=prod/ns=${namespace}/year=${S_YEAR}/month=${S_MONTH}/day=${S_DAY}/hour=${S_HOUR}/logs"
        )
```

The Python S3 destination's periodic flush thread terminated with:

```text
Exception in thread Thread-14207:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1433, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/syslog-ng/python/syslogng/modules/s3/s3_destination.py", line 368, in __flush_timed_out_s3_objects
    for s3_object in self.s3_objects.values():
RuntimeError: dictionary changed size during iteration
```

`__flush_timed_out_s3_objects()` iterates directly over self.s3_objects.values():
```python
for s3_object in self.s3_objects.values():
    if should_flush_s3_object(s3_object, now):
        self.__finish_s3_object(s3_object)
```
At the same time, the message processing path can add a new target:
```python
if target_key not in self.s3_objects:
    s3_object = self.s3_objects[target_key] = \
        self.__create_initial_s3_object(target_key, timestamp)
```
When an insertion happens during iteration, Python raises `RuntimeError: dictionary changed size during iteration.`
The call that schedules the next timer is at the end of the callback:
```
self.__start_flush_poll_timer()
```
Because the exception exits the callback before reaching this call, the periodic cleanup thread **is never started again**.
Consequences observed:
- Timed-out, partially filled compressed S3 objects stopped being finalized.
- Low-volume object buffers accumulated indefinitely, and memory usage keeps growing (memleak)

### Workaround
Our current workaround keeps `object-key()` bounded and puts the rotating partition in `object-key-timestamp()`:
```
object-key("logs/env=prod/ns=${namespace}/logs")
object-key-timestamp(
    "/year=${S_YEAR}/month=${S_MONTH}/day=${S_DAY}/hour=${S_HOUR}/logs"
)
```
This prevents continuous growth of the self.s3_objects dictionary, but it also changes the resulting object path because the current implementation inserts `-` between object-key() and object-key-timestamp().

**Comment by alltilla** [comment]
Hello @lars-planvera 

I opened a PR that intends to fix this issue among others.
