### ISSUE TITLE
Crash with interactive debugger and reload

### ISSUE THREAD

**Issue by alltilla** [axoflow/axosyslog#378]
# AxoSyslog
## Version of AxoSyslog
4.9.0

# Steps to reproduce

### `syslog-ng.conf`
```
log "internal_messages_to_stderr" {
  source{ internal(); };
  destination {
    file("/dev/stderr");
  };
};

log {
  source { example-msg-generator(); };

  rewrite {
    set("syslog-ng-test" value(topic));
  };
};
```

### terminal 1
```
./install/sbin/syslog-ng -Fe
```

### terminal 2
```
./install/sbin/syslog-ng-ctl attach debugger
```

### terminal 3
```
./install/sbin/syslog-ng-ctl reload
```

### terminal 2
```
c
c
```

### terminal 1
CRASH
```
Thread 4 "syslog-ng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef4006c0 (LWP 90602)]
0x00007ffff7f1f79e in zone_info_get_offset (self=0xeabc27d7444505cf, timestamp=1731398027) at ../lib/timeutils/zoneinfo.c:448
448       if (self->transitions == NULL)
(gdb) bt
#0  0x00007ffff7f1f79e in zone_info_get_offset (self=0xeabc27d7444505cf, timestamp=1731398027) at ../lib/timeutils/zoneinfo.c:448
#1  0x00007ffff7f1fc3e in time_zone_info_get_offset (self=0x555555617c30, stamp=1731398027) at ../lib/timeutils/zoneinfo.c:530
#2  0x00007ffff7eed090 in log_macro_expand_date_time (id=28, options=0x7fffef3fd690, msg=0x55555561d320, result=0x7fffe8002310, type=0x7fffef3fd1c8 "") at ../lib/template/macros.c:347
#3  0x00007ffff7eefec3 in log_macro_expand (id=28, options=0x7fffef3fd690, msg=0x55555561d320, result=0x7fffe8002310, type=0x7fffef3fd4ab "\377") at ../lib/template/macros.c:729
#4  0x00007ffff7ef0a37 in log_template_append_elem_macro (self=0x7fffe8001f10, e=0x7fffe8002040, options=0x7fffef3fd690, msg=0x55555561d320, type=0x7fffef3fd52b "\377\001", result=0x7fffe8002310)
    at ../lib/template/eval.c:92
#5  0x00007ffff7ef1172 in log_template_append_format_value_and_type_with_context (self=0x7fffe8001f10, messages=0x7fffef3fd5c0, num_messages=1, options=0x7fffef3fd690, result=0x7fffe8002310, type=0x0)
    at ../lib/template/eval.c:197
#6  0x00007ffff7ef13e1 in log_template_append_format_value_and_type (self=0x7fffe8001f10, lm=0x55555561d320, options=0x7fffef3fd690, result=0x7fffe8002310, type=0x0) at ../lib/template/eval.c:251
#7  0x00007ffff7ef14a0 in log_template_format_value_and_type (self=0x7fffe8001f10, lm=0x55555561d320, options=0x7fffef3fd690, result=0x7fffe8002310, type=0x0) at ../lib/template/eval.c:265
#8  0x00007ffff7ef1568 in log_template_format (self=0x7fffe8001f10, lm=0x55555561d320, options=0x7fffef3fd690, result=0x7fffe8002310) at ../lib/template/eval.c:280
#9  0x00007ffff7f065b1 in _display_msg_with_template (self=0x7fffe8001e50, msg=0x55555561d320, template=0x7fffe8001f10) at ../lib/debugger/debugger.c:88
#10 0x00007ffff7f06f20 in _handle_interactive_prompt (self=0x7fffe8001e50) at ../lib/debugger/debugger.c:357
#11 0x00007ffff7f06fc5 in _debugger_thread_func (self=0x7fffe8001e50) at ../lib/debugger/debugger.c:380
#12 0x00007ffff7d03c82 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff7a9ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#14 0x00007ffff7b29c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by alltilla** [comment]
Found during the review of #327, but probably not introduced there.
